apiVersion: v1
kind: Service
metadata:
  labels:
    run: busybox
  name: busybox
  namespace: default  
spec:
  clusterIP: 10.100.35.202
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: busybox
    version: "$GREEN_VERSION"
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}